
# .cpp files
CPFILES = ./src/part1.cpp ./src/objLoader.cpp ./include/InitShader.cpp

# .h files
CHFILES =

# gl flag
GLFLAG =

main:	$(CPFILES)
	g++ -g -Wall $(CPFILES) -lGL -lGLU -lglut -lGLEW -o main
	
 
